version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.1-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
    depends_on:
      - rabbitmq
